[bot]
# log level, debug/info
log_level = "info"
# send additional debug info for openrouter requests as reply into chat
debug_replies = false

[chat]
# Timeout to clear conversation cache per ChatID
context_timeout = "5m"
system_prompt = '''
You are HSBot, a helpful assistant.
There might be multiple persons in a single conversation interacting with you.
The username of the person is at the beginning of the prompt, starting with an @.
If there is no @, it's just the first name of the user. You can directly address a person if you got provided with an @ handle.
You support multiple models, for a list of available models, the user can type '/models'.
A user can interact with any model by using a '#' followed by the keyword, for example '/chat #gpt prompt goes here'.
'''
voice_prompt_addition = '''
Important:  For the next message, you are generating audio. Discard all emojis.
Call the usernames without '@'. Use proper punctuation
to make speech natural.

Add emotional or stylistic cues in square brackets within your text:

"[happy] What a beautiful day!"
"[sad] I'm sorry to hear that."
"[excited] This is amazing news!"

The output will interpret these markers and adjust the voice accordingly.
Control volume, intensity, and emphasis. Place [emphasis] right before the word or phrase you want to stress:

"This is [emphasis] really important."

Add natural human sounds:

Laughing: "[laughing] Ha, ha, ha"
Sobbing: "[sobbing]"
Crying Loudly:	"[crying loudly]"
Sighing: "[sighing] sigh"
Yawning: "[yawning] yawn"
'''

[handler]
# timeout for actions initiated by the command handler
timeout = "30s"

[telegram]
bot_token = "4242:telegram-bot-token"
# admin telegram username for info about getting authorized
admin_username = "admin_username"
# authorized telegram chat IDs
allowed_chat_ids = [ -4242424242, 424242424242 ]
# daily spending limit in dollars, resets at 00:00 local time
daily_spend_limit = 1.00
api_url = "https://api.telegram.org"

[openrouter]
api_key = "sk-api-key"
# define a list of openrouter models here. add at least one default model with a priority.
# on provider errors, the default models will all be consecutively tried for the request.
models = [
    { keyword = "claude", identifier = "anthropic/claude-sonnet-4", Default = 1},
    { keyword = "gpt", identifier = "openai/gpt-4.1", Default = 2},
    { keyword = "gemini", identifier = "google/gemini-2.5-pro-preview"},
    { keyword = "grok", identifier = "x-ai/grok-3-beta"},
    { keyword = "deepseek", identifier = "deepseek/deepseek-chat-v3-0324"},
    { keyword = "unslop", identifier = "thedrummer/unslopnemo-12b"},
]
tts_model = "fish-audio/s2.1-pro"
stt_model = "openai/whisper-large-v3-turbo"
voices = [
    { keyword = "default", identifier = "b347db033a6549378b48d00acb0d06cd", Default = 1},
]
image_models = [
    { keyword = "flash", identifier = "google/gemini-2.5-flash-image", Default = 1},
    { keyword = "gpt", identifier = "openai/gpt-image-1"},
]